### ISSUE TITLE
There is a problum with GPIO19 for micropython

### ISSUE THREAD

**Issue by CaptainJackey** [raspberrypi/pico-micropython-examples#7] opened 2021-01-29 04:58 UTC
It can't control high or low with machine.Pin with GIOP19, no higt or low output, but 18, 20 is OK!  please cheak!

**Test code as follow:**

from machine import Pin
import time

LED1 = Pin(18, Pin.OUT)

LED1.high()
time.sleep_ms(1000)
LED1.low()
time.sleep_ms(1000)

**Comment by lurch** [comment] 2021-01-29 08:54
Duplicate of https://github.com/raspberrypi/pico-sdk/issues/28 which is fixed by https://github.com/raspberrypi/pico-sdk/pull/31 , so this should hopefully be fixed in the next release of MicroPython.

**Comment by CaptainJackey** [comment] 2021-01-29 08:59
> Duplicate of [raspberrypi/pico-sdk#28](https://github.com/raspberrypi/pico-sdk/issues/28) which is fixed by [raspberrypi/pico-sdk#31](https://github.com/raspberrypi/pico-sdk/pull/31) , so this should hopefully be fixed in the next release of MicroPython.

So when will the official website UF2 File will be updated? https://www.raspberrypi.org/documentation/pico/getting-started/

**Comment by aallan** [comment] 2021-01-29 09:06
As soon as possible after the fix has propagated through the repos and all the PRs resolve themselves. We're expecting to do a new SDK release shortly which should resolve the issue. I can then build a new MicroPytyhon binary.

**Comment by aallan** [comment] 2021-01-29 14:23
Looks like the PR just got merged into MicroPython mainline,https://github.com/micropython/micropython/pull/6791#issuecomment-769832231. Not sure that includes the fix though.

**Comment by dpgeorge** [comment] 2021-01-31 12:11
> Not sure that includes the fix though.

It doesn't include it.  We are using the master branch of pico-sdk which doesn't yet have the GPIO19 fix.

**Comment by lurch** [comment] 2021-02-01 21:25
@dpgeorge https://github.com/raspberrypi/pico-sdk/releases/tag/1.0.1 has just been pushed :slightly_smiling_face:

**Comment by dpgeorge** [comment] 2021-02-02 00:02
This should now be fixed in MicroPython mainline, see https://github.com/micropython/micropython/pull/6826

**Comment by aallan** [comment] 2021-02-02 09:03
Nightly builds available from https://micropython.org/download/rp2-pico/

**Closed** 2021-02-02 09:03 UTC
Labels: paused, upstream
