### ISSUE TITLE
multicore example does not work on Pico

### ISSUE THREAD

**Issue by jbeale1** [raspberrypi/pico-micropython-examples#28] opened 2021-04-03 19:23 UTC
Running this example code from Thonny version 3.3.5 (hosted on Pi 4B) on Pico MicroPython v1.14, generates several errors as shown below. This is also discussed here: https://www.raspberrypi.org/forums/viewtopic.php?f=146&t=308150

https://github.com/raspberrypi/pico-micropython-examples/blob/master/multicore/multicore.py

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/thonny/workbench.py", line 1708, in event_generate
    handler(event)
  File "/usr/lib/python3/dist-packages/thonny/shell.py", line 433, in _handle_program_output
    self._update_visible_io(None)
  File "/usr/lib/python3/dist-packages/thonny/shell.py", line 512, in _update_visible_io
    self._apply_io_event(data, stream_name)
  File "/usr/lib/python3/dist-packages/thonny/shell.py", line 555, in _apply_io_event
    self.active_extra_tags.pop()
IndexError: pop from empty list

MicroPython v1.14 on 2021-03-28; Raspberry Pi Pico with RP2040
Type "help()" for more information.
>>> %Run -c $EDITOR_CONTENT
THONNY FAILED TO EXECUTE COMMAND Run

SCRIPT:

class __thonny_helper:
    try:
        import uos as os
    except ImportError:
        import os
    import sys

    # for object inspector
    inspector_values = dict()
    last_repl_values = []
    @classmethod
    def print_repl_value(cls, obj):
        if obj is not None:
            cls.last_repl_values.append(obj)
            cls.last_repl_values = cls.last_repl_values[-5:]
            print('[object_link_for_thonny=%d]' % id(obj), repr(obj), '', sep='')

    @staticmethod
    def print_mgmt_value(obj):
        print('<thonny>', repr(obj), '</thonny>', sep='', end='')

    @staticmethod
    def repr(obj):
        try:
            s = repr(obj)
            if len(s) > 50:
                s = s[:50] + "..."
            return s
        except Exception as e:
            return "<could not serialize: " + str(e) + ">"

    @classmethod
    def listdir(cls, x):
        if hasattr(cls.os, "listdir"):
            return cls.os.listdir(x)
        else:
            return [rec[0] for rec in cls.os.ilistdir(x) if rec[0] not in ('.', '..')]

    @classmethod
    def getcwd(cls):
        if hasattr(cls, "getcwd"):
            return cls.os.getcwd()
        else:
            # micro:bit
            return ""

    @classmethod
    def chdir(cls, x):
        return cls.os.chdir(x)

    @classmethod
    def rmdir(cls, x):
        return cls.os.rmdir(x)

STDOUT:

STDERR:
Traceback (most recent call last):
  File "<stdin>", line 7
SyntaxError: invalid syntax

ManagementError
>>> done
THONNY FAILED TO EXECUTE COMMAND get_globals

SCRIPT:
__thonny_helper.print_mgmt_value({name : (__thonny_helper.repr(value), id(value)) for (name, value) in globals().items() if not name.startswith('__')})

STDOUT:

STDERR:
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
NameError: name '__thonny_helper' isn't defined

**Comment by lurch** [comment] 2021-04-03 19:40
Looks like this is a duplicate of #17 which contains more information? And which also says "The problem may not manifest outside of Thonny, depending on how you are using it. For example, when you save your code as main.py and (soft) reboot, and you leave the REPL alone when the main thread finishes, then you don't see this problem." :shrug:

**Closed** 2021-04-03 19:48 UTC
Labels: duplicate
